package com.news.lyt.domain;

public class Collection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.id
     *
     * @mbggenerated Thu Jun 25 10:47:19 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.uid
     *
     * @mbggenerated Thu Jun 25 10:47:19 CST 2020
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.nid
     *
     * @mbggenerated Thu Jun 25 10:47:19 CST 2020
     */
    private Integer nid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.id
     *
     * @return the value of collection.id
     *
     * @mbggenerated Thu Jun 25 10:47:19 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.id
     *
     * @param id the value for collection.id
     *
     * @mbggenerated Thu Jun 25 10:47:19 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.uid
     *
     * @return the value of collection.uid
     *
     * @mbggenerated Thu Jun 25 10:47:19 CST 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.uid
     *
     * @param uid the value for collection.uid
     *
     * @mbggenerated Thu Jun 25 10:47:19 CST 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.nid
     *
     * @return the value of collection.nid
     *
     * @mbggenerated Thu Jun 25 10:47:19 CST 2020
     */
    public Integer getNid() {
        return nid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.nid
     *
     * @param nid the value for collection.nid
     *
     * @mbggenerated Thu Jun 25 10:47:19 CST 2020
     */
    public void setNid(Integer nid) {
        this.nid = nid;
    }
}