package com.news.lyt.domain;

import java.util.Date;

public class NewsSerach {

    private String text;

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    @Override
    public String toString() {
        return "NewsSerach{" +
                "text='" + text + '\'' +
                ", id=" + id +
                ", cid=" + cid +
                ", newsname='" + newsname + '\'' +
                ", looknum=" + looknum +
                ", replynum=" + replynum +
                ", time='" + time + '\'' +
                ", photoaddress='" + photoaddress + '\'' +
                ", textaddress='" + textaddress + '\'' +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.id
     *
     * @mbggenerated Thu Jun 25 10:47:19 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.cid
     *
     * @mbggenerated Thu Jun 25 10:47:19 CST 2020
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.newsname
     *
     * @mbggenerated Thu Jun 25 10:47:19 CST 2020
     */
    private String newsname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.looknum
     *
     * @mbggenerated Thu Jun 25 10:47:19 CST 2020
     */
    private Integer looknum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.replynum
     *
     * @mbggenerated Thu Jun 25 10:47:19 CST 2020
     */
    private Integer replynum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.time
     *
     * @mbggenerated Thu Jun 25 10:47:19 CST 2020
     */
    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.photoaddress
     *
     * @mbggenerated Thu Jun 25 10:47:19 CST 2020
     */
    private String photoaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.textaddress
     *
     * @mbggenerated Thu Jun 25 10:47:19 CST 2020
     */
    private String textaddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.id
     *
     * @return the value of news.id
     *
     * @mbggenerated Thu Jun 25 10:47:19 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.id
     *
     * @param id the value for news.id
     *
     * @mbggenerated Thu Jun 25 10:47:19 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.cid
     *
     * @return the value of news.cid
     *
     * @mbggenerated Thu Jun 25 10:47:19 CST 2020
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.cid
     *
     * @param cid the value for news.cid
     *
     * @mbggenerated Thu Jun 25 10:47:19 CST 2020
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.newsname
     *
     * @return the value of news.newsname
     *
     * @mbggenerated Thu Jun 25 10:47:19 CST 2020
     */
    public String getNewsname() {
        return newsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.newsname
     *
     * @param newsname the value for news.newsname
     *
     * @mbggenerated Thu Jun 25 10:47:19 CST 2020
     */
    public void setNewsname(String newsname) {
        this.newsname = newsname == null ? null : newsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.looknum
     *
     * @return the value of news.looknum
     *
     * @mbggenerated Thu Jun 25 10:47:19 CST 2020
     */
    public Integer getLooknum() {
        return looknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.looknum
     *
     * @param looknum the value for news.looknum
     *
     * @mbggenerated Thu Jun 25 10:47:19 CST 2020
     */
    public void setLooknum(Integer looknum) {
        this.looknum = looknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.replynum
     *
     * @return the value of news.replynum
     *
     * @mbggenerated Thu Jun 25 10:47:19 CST 2020
     */
    public Integer getReplynum() {
        return replynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.replynum
     *
     * @param replynum the value for news.replynum
     *
     * @mbggenerated Thu Jun 25 10:47:19 CST 2020
     */
    public void setReplynum(Integer replynum) {
        this.replynum = replynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.time
     *
     * @return the value of news.time
     *
     * @mbggenerated Thu Jun 25 10:47:19 CST 2020
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.time
     *
     * @param time the value for news.time
     *
     * @mbggenerated Thu Jun 25 10:47:19 CST 2020
     */
    public void setTime(String time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.photoaddress
     *
     * @return the value of news.photoaddress
     *
     * @mbggenerated Thu Jun 25 10:47:19 CST 2020
     */
    public String getPhotoaddress() {
        return photoaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.photoaddress
     *
     * @param photoaddress the value for news.photoaddress
     *
     * @mbggenerated Thu Jun 25 10:47:19 CST 2020
     */
    public void setPhotoaddress(String photoaddress) {
        this.photoaddress = photoaddress == null ? null : photoaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.textaddress
     *
     * @return the value of news.textaddress
     *
     * @mbggenerated Thu Jun 25 10:47:19 CST 2020
     */
    public String getTextaddress() {
        return textaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.textaddress
     *
     * @param textaddress the value for news.textaddress
     *
     * @mbggenerated Thu Jun 25 10:47:19 CST 2020
     */
    public void setTextaddress(String textaddress) {
        this.textaddress = textaddress == null ? null : textaddress.trim();
    }
}